sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - wget --no-check-certificate "https://cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.tar.gz"
  - tar xf ./cmake-3.6.3-Linux-x86_64.tar.gz
  - export PATH=$PATH:$PWD/cmake-3.6.3-Linux-x86_64/bin/

script:
  - ./scripts/install-cmake.sh
  - mkdir build && cd build
  - cmake ..
  - make
  - ./xtra_test
  - ./xtra_benchmark

push.defaultnotifications:
  email: true