sudo: false

language:
  - cpp

addons:
  apt:
    packages:
      - cmake
    sources:
      - ubuntu-toolchain-r-test
      - kalakris-cmake

script:
  - ./scripts/install-cmake.sh
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./xtra_test
  - ./xtra_benchmark

push.defaultnotifications:
  email: true