sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./xtra_test
  - ./xtra_benchmark

push.defaultnotifications:
  email: true